version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Test1234"
      POSTGRES_DB: "BlogCase"
      TZ: "Europe/Istanbul"
    ports:
      - "1400:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data: